- Package.swift
- README.md
* Updates README regarding the Transifex token and secret usage in ObjC
apps.
* Removes `TXNativeExtensions.swift` file from `TransifexNative` target
to silence the import warning.
> Apply minor fixes

- README.md
- Sources/TransifexNative/Core.swift
- Sources/TransifexNative/Locales.swift
- Tests/TransifexNativeTests/TransifexNativeTests.swift
This pull request includes fixes regarding the `CurrentLocaleProvider` protocol (now renamed to `TXCurrentLocaleProvider`) and the `UserDefaultsLocaleProvider` (now renamed to `TXPreferredLocaleProvider`) that now uses the `NSLocale.autoupdatingCurrent` property.
Also address a number of small issues regarding the documentation of the `LocaleState` class and introduces a new property (`translatedLocales`) that's used by the `CDSHandler` when fetching the translations from the server.
> Locale related fixes

- .github/workflows/swift.yml
- README.md
- Sources/TransifexNative/CDSHandler.swift
- Sources/TransifexNative/Cache.swift
- Sources/TransifexNative/Core.swift
- Tests/TransifexNativeTests/TransifexNativeTests.swift
The `fetchTranslations` method now offers a completion handler so that
the caller is notified when the downloading of the translations is
complete.
The completion block of that method now also reports any errors that
may have been encountered during the download operation so that the
caller can decide how the resulting translations should be treated.
`LocaleStrings` and all of the depended type aliases have now a `TX`
prefix to avoid any unwanted naming collisions.
Caching logic has been improved: If an object that conforms to the `TXCache`
protocol (which has also been renamed) isn't provided during the
`TxNative` initialization, then the internal `MemoryCache` is used,
which during its initialization looks up both in the main app bundle and
in the application directory to find any …
> Improve pull logic, refactor cache

- CHANGELOG.md
- Sources/Transifex/Core.swift
- Sources/Transifex/Locales.swift
- Tests/TransifexTests/TransifexTests.swift
`TXPreferredLocaleProvider` used to rely on the `NSLocale.autoupdatingCurrent` property to fetch the current locale of
the device, but the property was not returning the correct language code.
The updated code looks into the `preferredLanguages` property list of the `Locale` class instead, and if that list is not empty (which is usually the case), picks the first language and sets it as the current locale, which reflects the user choice.
On top of that, a new unit test method is added that adds the greek language in the list of the preferred languages and asserts whether that language code is returned by the `TXLocaleState.currentLocale` property.
Last, some existing unit tests that were not running are not enabled.
> Preferred locale provider returns correct language code

- CHANGELOG.md
- README.md
- Sources/Transifex/Cache.swift
- Sources/Transifex/Core.swift
- Tests/TransifexTests/TransifexTests.swift
Refactors cache policies based on the latest discussion between
@dbendilas and @petrakeas.
The empty translations (`""`) are now added in the cache (depending on
the policy) and they are not filtered out.
A helpful cheat-sheet table has been added in the documentation of the
`TXCacheOverridePolicy` and the policy documentation has been also
updated.
The cache now defaults to the `.overrideUsingTranslatedOnly` instead of
the `.overrideAll` policy, if no policy is specified by the developer.
If a cache entry is found to contain an empty string during rendering,
the logic falls back to the missing policy.
The documentation of the `TXDiskCacheProvider` has been updated to
declare that it initializes the disk cache provider synchronously.
> Refactor cache policies

- CHANGELOG.md
- README.md
- Sources/Transifex/Cache.swift
- Sources/Transifex/Core.swift
- Sources/Transifex/Locales.swift
- Tests/TransifexTests/TransifexTests.swift
> Release: 0.1.1

- CHANGELOG.md
- Sources/Transifex/Core.swift
Bumps the Transifex SDK version from 0.1.2 to 0.1.3 so that the
`TXNative.version` value matches the value of the SDK version git tag.
> Bump SDK version to 0.1.3

- CHANGELOG.md
- Sources/Transifex/Cache.swift
- Sources/Transifex/Core.swift
* Exposes `TXStandardCache` `getCache` static method to Objective-C.
* Updates Changelog and version
> Expose getCache method to ObjC

- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
- Tests/TransifexTests/TransifexTests.swift
Adds an optional argument to `TXNative.fetchTranslations` method
(`tags`) that allows users to define a set of tags to use when fetching
translations from CDS. If defined, CDS will only return content for
strings that have all of the given tags.
Adds unit test that expects the final URL sent to server to have a
specific format.
> Fetch content with tags only

- CHANGELOG.md
- Sources/Transifex/Core.swift
- Sources/Transifex/Policies.swift
- Tests/TransifexTests/TransifexTests.swift
* `TXErrorPolicy` method `get()` is now marked as being able to throw
an exception.
* Exceptions thrown by the `get()` method are now caught by the
`render()` method of the `NativeCore` class. If an exception is caught,
it's logged and the "ERROR" string (`ERROR_FALLBACK`) is returned.
* `TXRenderedSourceErrorPolicy` now returns the string to render instead
of the source string so that the user will not see any placeholders in
the UI.
* Updates the documentation of the `TXRenderedSourceErrorPolicy` to
reflect the changes.
* Adds unit test regarding the "ERROR" string if the error policy throws
an exception.
> Improve error policy behavior

- CHANGELOG.md
- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
- Tests/TransifexTests/TransifexTests.swift
* Updates `CDSHandler` logic so that it can work with the version 2
of the CDS documentation.
* Updates the response data structures that the new CDS version produces.
* Updates the push logic with the new job oriented approach.
* Updates unit test logic.
* Adds unit tests for the new job oriented approach on push.
> Update CDSHandler logic to v2

- CHANGELOG.md
- Sources/Transifex/Core.swift
Uses the source string as the key for cache lookup when rendering a
localized translation.
As a fallback, if the entry is not found, the logic also uses the hash
of that source string as a key for cache lookup.
> Lookup source string as key to cache 

- .github/workflows/swift.yml
- CHANGELOG.md
- Sources/Transifex/Core.swift
- Sources/Transifex/Locales.swift
- Tests/TransifexTests/TransifexTests.swift
The `TXPreferredLocaleProvider` class does not always report the current
locale to be used for localization correctly.
This is because the `TXPreferredLocaleProvider` implementation always
returns the first supported language from the Settings app, as set by
the user. That language, though, is not always the correct candidate, as
it might not be the most appropriate localization candidate, or not even
a valid candidate at all in some cases.
For example:
If user has set the following languages as their preference in the
Settings app: "Dutch", "French" and the supported languages for
localization in the app are "French", "English", "German", "Spanish"
and "Italian" then the correct language should be "French" and not
"Dutch" that is the first preferred language of the user.
Similarly, if …
> Refactor TXPreferredLocaleProvider logic

- .github/workflows/swift.yml
- CHANGELOG.md
- Sources/Transifex/Core.swift
- Sources/Transifex/Locales.swift
- Tests/TransifexTests/TransifexTests.swift
#48 : Refactor TXPreferredLocaleProvider logic
> Release: 1.0.3

- CHANGELOG.md
- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
- Tests/TransifexTests/TransifexTests.swift
Adds support for filtering the fetched translations either by a list of
tags and/or by status.
The filtering can be either specified globally on the TXNative
initialization by passing the `filterTags` and/or the `filterStatus`
properties, or it can be specified every time the `fetchTranslations()`
method is called. In the latter case, the passed tags or status will
have a priority over any already specified tags or status specified
during initialization.
The `session` property in the `TXNative` initialization is now used
correctly.
The unit tests have been updated to test both the `TXNative` and the
`CDSHandler` behavior on translation filtering using tags and status.
Due to the number of different arguments on the `CDSHandler`
initialization, a separate struct was created to hold this …
> Implement proper tag and status filter support

- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
- Tests/TransifexTests/TransifexTests.swift
The `pushTranslations()` method now returns a secondary array of `Error`
objects in the completion handler that represents the generated warnings
during the processing of the source strings that are non-fatal but can
be of interest to the developer.
This change introduces a new enum (`TXCDSWarning`) that hosts those
warnings, like duplicate source string and empty key detection.
The `pushTranslations()` logic has been improved by implementing the
following changes:
* `serializeTranslations()` is now a private static method as it does
not need to look into the state of the `CDSHandler` instance.
* That method now returns a tuple that includes a `Result<Data>` object
as the first member, revealing whether the serialization
was successful, thus offering the `Data` object, or a failure, thus …
> Various improvements

- CHANGELOG.md
- README.md
- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
Introduces the `TXPushConfiguration` object that can hold the different configuration options available for the push translations functionality and adds any missing options:
* Adds `overrideTags`, `overrideOccurrences`, `keepTranslations` and `dryRun` options.
* Moves `purge` inside the `TXPushConfiguration`.
* Ensures that the proper JSON keys are used when encoding the above options.
* Adds documentation.
* Replaces the `purge` argument of the `pushTranslations()` methods with the `TXPushConfiguration` object, ensuring that the default value holds the correct default values for each option.
* Fixes small typo on README.
> Introduce push configuration

- CHANGELOG.md
- README.md
- Sources/Transifex/Core.swift
#59 : Update README
#60 : Update README
#61 : Version 2.0.1
> Release: 2.0.1

- CHANGELOG.md
- Sources/Transifex/Cache.swift
- Sources/Transifex/Core.swift
- Sources/Transifex/Plurals.swift
- Sources/Transifex/RenderingStrategy.swift
- Tests/TransifexTests/TransifexTests.swift
With the introduction of the String Catalogs file format in Xcode 15,
developers have now the option to create localizations that vary by
device and/or by plural. On top of that, multiple tokens can be added in
a localized phrase (also known as substitutions) that can also support
the aforementioned variations.
In order to support all those new formats as well as the old
substitution rules found in the Strings Dictionary format
(`.stringsdict`), the advanced rules from the CLI tool are formatted as
an intermediate XML structure and pushed to CDS.
Once those XML structures are pulled from CDS by the application, they
need to be properly parsed and formatted in a way so that they are ready
for presentation when needed by the application. During the phase when
the SDK populates its cache, …
> Full String Catalog support

- .github/workflows/swift.yml
- CHANGELOG.md
- Package.swift
- README.md
- Sources/Transifex/Core.swift
- Sources/Transifex/RenderingStrategy.swift
- Sources/Transifex/Swizzler.swift
- Sources/TransifexObjCRuntime/TXNativeObjcSwizzler.m
- Sources/TransifexObjCRuntime/include/TXNativeObjcSwizzler.h
- Tests/TransifexObjCTests/TXNativeObjcSwizzlerTests.m
- Tests/TransifexTests/TransifexTests.swift
* Adds attributed string swizzling that allows Transifex SDK to allow
for SwiftUI support.
* De-swizzles methods when SDK is deactivated (when `dispose` is
called).
* Adds public static method to deactivate swizzling on passed `Bundle`
instance.
* Ensures that the special Transifex `.stringsdict` key used to
calculate the plural rules, cannot be swizzled
(`TRANSIFEX_STRINGSDICT_KEY`).
* Ensures that SDK is properly deactivated when a unit test finishes, so
that swizzling is re-applied correctly on each test.
* Adds unit test for the `localizedAttributedString:...` method in
Objective-C.
* Adds unit test for the `NSLocalizedString()` method in Swift.
NOTE: SwiftUI elements (`View`, `Button` etc) cannot be added to unit
tests.
---
* Bumps `TXNative.version` to 2.0.3.
* Updates CHANGELOG …
> SwiftUI support

- .github/workflows/swift.yml
- CHANGELOG.md
- Package.swift
- README.md
- Sources/Transifex/Core.swift
- Sources/Transifex/RenderingStrategy.swift
- Sources/Transifex/Swizzler.swift
- Sources/TransifexObjCRuntime/TXNativeObjcSwizzler.m
- Sources/TransifexObjCRuntime/include/TXNativeObjcSwizzler.h
- Tests/TransifexObjCTests/TXNativeObjcSwizzlerTests.m
- Tests/TransifexTests/TransifexTests.swift
> Release: 2.0.3

- CHANGELOG.md
- Package.swift
- README.md
- Sources/Transifex/Core.swift
- Tests/TransifexObjCTests/TXNativeObjcSwizzlerTests.m
Updates minimum supported OS versions on the package manifest
and on README.
Also updates the `testAttributed` unit test target availability
decorator with the supported OS versions.
Minimum Xcode version was updated to match the latest Xcode
release (15.4).
---
* Bumps `TXNative.version` to 2.0.4.
* Updates CHANGELOG with the changes implemented for 2.0.4.
> Update minimum supported versions

- CHANGELOG.md
- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Cache.swift
- Sources/Transifex/Core.swift
- Sources/Transifex/Plurals.swift
* Ensures that callbacks won't capture `self` strongly.
* Ensures "Designed for iPhone"/ "Designed for iPad" apps use the proper device name.
* Discloses that completion handlers are called from background threads.
* Improves cache update after a `fetchTranslations` call.
> Version 2.0.5

- .github/workflows/docs.yml
MacOS 12 runner was failing when trying to build the project for the `jazzy` gem that generates the documentation.
> Updates docs CI runner image from MacOS 12 to MacOS 14

- .github/workflows/docs.yml
#72 : Updates docs CI runner image from MacOS 12 to MacOS 14
> Release: 2.0.5

- CHANGELOG.md
- README.md
- Sources/Transifex/CDSHandler.swift
- Sources/Transifex/Core.swift
- Sources/Transifex/Plurals.swift
#74 : Improve documentation
#75 : Bump version to 2.0.6
> Release: 2.0.6
